import 'app_language.dart';

class AppText {
  final AppLanguage language;

  const AppText(this.language);

  String t(String key) {
    switch (language) {
      case AppLanguage.english:
        return key;
      case AppLanguage.myanmar:
        return _translate(key, _myanmar);
      case AppLanguage.chinese:
        return _translate(key, _chinese);
    }
  }

  String _translate(String key, Map<String, String> translations) {
    final direct = translations[key];
    if (direct != null) return direct;

    if (key.endsWith(' required')) {
      final label = key.substring(0, key.length - ' required'.length);
      final translatedLabel = translations[label] ?? label;
      return language == AppLanguage.chinese
          ? '$translatedLabel为必填项'
          : '$translatedLabel ဖြည့်ရန်လိုအပ်သည်';
    }

    final checklistMatch = RegExp(r'^Checklist (\d+)$').firstMatch(key);
    if (checklistMatch != null) {
      final number = checklistMatch.group(1)!;
      return language == AppLanguage.chinese
          ? '检查项 $number'
          : 'စစ်ဆေးချက် $number';
    }

    return key;
  }
}

const Map<String, String> _myanmar = {
  '\$label required': '\$label ဖြည့်ရန်လိုအပ်သည်',
  'Access SOPs, recipes, and ingredients': 'SOP၊ ချက်နည်းနှင့် ပါဝင်ပစ္စည်းများကို ကြည့်ရှုရန်',
  'Active': 'အသုံးပြုနေသည်',
  'Advertisement': 'ကြော်ငြာ',
  'Actor': 'လုပ်ဆောင်သူ',
  'Actors': 'လုပ်ဆောင်သူများ',
  'Actual received': 'အမှန်တကယ် လက်ခံရရှိမှု',
  'Add SKU': 'SKU ထည့်ရန်',
  'Add Supplier': 'ပေးသွင်းသူ ထည့်ရန်',
  'Add Tag': 'Tag ထည့်ရန်',
  'Add any additional notes...': 'အပိုမှတ်ချက် ထည့်ပါ...',
  'Address': 'လိပ်စာ',
  'All': 'အားလုံး',
  'All Time': 'အချိန်အားလုံး',
  'All supplier messages copied': 'ပေးသွင်းသူ စာများအားလုံး ကူးယူပြီး',
  'Apply': 'အသုံးပြုရန်',
  'Approvals': 'အတည်ပြုမှုများ',
  'Approve': 'အတည်ပြုရန်',
  'Approve All': 'အားလုံး အတည်ပြုရန်',
  'Approved': 'အတည်ပြုပြီး',
  'Assign': 'တာဝန်ပေးရန်',
  'Assign SKU to user': 'SKU ကို အသုံးပြုသူထံ တာဝန်ပေးရန်',
  'Assign SKU to user.': 'SKU ကို အသုံးပြုသူထံ တာဝန်ပေးပါ။',
  'Assigned': 'တာဝန်ပေးပြီး',
  'Assigned tags cannot be deleted': 'အသုံးပြုထားသော Tag များကို ဖျက်၍မရပါ',
  'Assignee': 'တာဝန်ခံ',
  'Assignee updated': 'တာဝန်ခံ ပြင်ဆင်ပြီး',
  'Attendance': 'တက်ရောက်မှု',
  'Attendance reports': 'တက်ရောက်မှု အစီရင်ခံစာများ',
  'Audit': 'စစ်ဆေးမှတ်တမ်း',
  'Audit Inbound': 'အဝင်ပစ္စည်း စစ်ဆေးမှတ်တမ်း',
  'Audit Trail': 'ပြောင်းလဲမှု မှတ်တမ်း',
  'Available for redemption': 'လဲလှယ်အသုံးပြုနိုင်သည်',
  'Average': 'ပျမ်းမျှ',
  'Back': 'နောက်သို့',
  'Backlog': 'ကျန်ရှိအလုပ်',
  'Balance': 'လက်ကျန်',
  'Balance must be Min / Max.': 'လက်ကျန်သည် အနည်းဆုံးနှင့် အများဆုံးကြား ဖြစ်ရမည်။',
  'Business': 'လုပ်ငန်း',
  'Camera only': 'ကင်မရာသာ',
  'Camera photo captured': 'ကင်မရာဓာတ်ပုံ ရိုက်ပြီး',
  'Cancel': 'ပယ်ဖျက်ရန်',
  'Capture photos, then SKU.': 'ဓာတ်ပုံရိုက်ပြီးနောက် SKU ရွေးပါ။',
  'Captured': 'ရိုက်ပြီး',
  'Career Path': 'အလုပ်အကိုင်လမ်းကြောင်း',
  'Change log': 'ပြောင်းလဲမှု မှတ်တမ်း',
  'Changed Value': 'ပြောင်းလဲတန်ဖိုး',
  'Checklist': 'စစ်ဆေးစာရင်း',
  'Checklist \${index + 1}': 'စစ်ဆေးချက် \${index + 1}',
  'Checklist checked': 'စစ်ဆေးစာရင်း အတည်ပြုပြီး',
  'Clear': 'ရှင်းရန်',
  'Clear All': 'အားလုံးရှင်းရန်',
  'Click to upload photo': 'ဓာတ်ပုံတင်ရန် နှိပ်ပါ',
  'Clock in/out': 'အလုပ်ဝင်/ထွက်',
  'Company ID': 'ကုမ္ပဏီ ID',
  'Complete all fields.': 'အချက်အလက်အားလုံး ဖြည့်ပါ။',
  'Complete tasks to earn points': 'ပွိုင့်ရရန် တာဝန်များပြီးစီးပါ',
  'Completed': 'ပြီးစီးပြီး',
  'Confirm': 'အတည်ပြုရန်',
  'Confirm Approve All': 'အားလုံး အတည်ပြုမည်ကို အတည်ပြုပါ',
  'Confirm Reject All': 'အားလုံး ပယ်ချမည်ကို အတည်ပြုပါ',
  'Confirm Submit All': 'အားလုံး တင်ပြမည်ကို အတည်ပြုပါ',
  'Contact': 'ဆက်သွယ်ရန်',
  'Contact Person': 'ဆက်သွယ်ရမည့်သူ',
  'Copy Message': 'စာကို ကူးယူရန်',
  'Count': 'ရေတွက်ရန်',
  'Count stock / receive goods / prepare restock': 'ကုန်ပစ္စည်းရေတွက်ခြင်း၊ လက်ခံခြင်းနှင့် ပြန်ဖြည့်ရန်ပြင်ဆင်ခြင်း',
  'Counted By': 'ရေတွက်သူ',
  'Create New SOP': 'SOP အသစ် ဖန်တီးရန်',
  'Create Role': 'ရာထူး ဖန်တီးရန်',
  'Create SOP': 'SOP ဖန်တီးရန်',
  'Create Supplier': 'ပေးသွင်းသူ ဖန်တီးရန်',
  'Create User': 'အသုံးပြုသူ ဖန်တီးရန်',
  'Create a Tag in Stock first.': 'Stock တွင် Tag ကို အရင်ဖန်တီးပါ။',
  'Create supplier first': 'ပေးသွင်းသူကို အရင်ဖန်တီးပါ',
  'Create suppliers': 'ပေးသွင်းသူများ ဖန်တီးရန်',
  'Create tag first': 'Tag ကို အရင်ဖန်တီးပါ',
  'Create/list SKU': 'SKU ဖန်တီး/စာရင်းကြည့်ရန်',
  'Create/list Supplier': 'ပေးသွင်းသူ ဖန်တီး/စာရင်းကြည့်ရန်',
  'Created By': 'ဖန်တီးသူ',
  'Created Date': 'ဖန်တီးသည့်ရက်',
  'Current': 'လက်ရှိ',
  'Current Balance': 'လက်ရှိလက်ကျန်',
  'Current Stock': 'လက်ရှိကုန်ပစ္စည်း',
  'Custom Category': 'စိတ်ကြိုက်အမျိုးအစား',
  'Daily Count Backlog': 'နေ့စဉ်ရေတွက်မှု ကျန်ရှိစာရင်း',
  'Daily Count Records': 'နေ့စဉ်ရေတွက်မှု မှတ်တမ်းများ',
  'Daily Count Review': 'နေ့စဉ်ရေတွက်မှု စစ်ဆေးရန်',
  'Daily Tasks': 'နေ့စဉ်တာဝန်များ',
  'Daily count approved': 'နေ့စဉ်ရေတွက်မှု အတည်ပြုပြီး',
  'Daily count records approved': 'နေ့စဉ်ရေတွက်မှု မှတ်တမ်းများ အတည်ပြုပြီး',
  'Daily count records rejected': 'နေ့စဉ်ရေတွက်မှု မှတ်တမ်းများ ပယ်ချပြီး',
  'Daily count rejected': 'နေ့စဉ်ရေတွက်မှု ပယ်ချပြီး',
  'Daily stock count submitted': 'နေ့စဉ်ကုန်ပစ္စည်းရေတွက်မှု တင်ပြပြီး',
  'Delete': 'ဖျက်ရန်',
  'Deleted': 'ဖျက်ပြီး',
  'Description': 'ဖော်ပြချက်',
  'Description:': 'ဖော်ပြချက်:',
  'Edit': 'ပြင်ဆင်ရန်',
  'Edit SOP': 'SOP ပြင်ဆင်ရန်',
  'Employee ID': 'ဝန်ထမ်း ID',
  'Enter a valid phone number.': 'မှန်ကန်သော ဖုန်းနံပါတ် ထည့်ပါ။',
  'Enter your password': 'စကားဝှက် ထည့်ပါ',
  'Entries': 'မှတ်တမ်းအရေအတွက်',
  'Example: 0123456789': 'ဥပမာ - 0123456789',
  'Example: 1kg damaged / item missing': 'ဥပမာ - ၁ ကီလို ပျက်စီး / ပစ္စည်းပျောက်',
  'Example: Chicken': 'ဥပမာ - ကြက်သား',
  'Example: Chiller': 'ဥပမာ - အအေးခန်း',
  'Example: Fresh Farm Supplier': 'ဥပမာ - Fresh Farm ပေးသွင်းသူ',
  'Example: GTI Kampar': 'ဥပမာ - GTI Kampar',
  'Example: Mr Tan': 'ဥပမာ - ဦးတန်',
  'Expected Outcome:': 'မျှော်မှန်းရလဒ်:',
  'Filter by assignee': 'တာဝန်ခံအလိုက် စစ်ထုတ်ရန်',
  'Gallery upload disabled': 'Gallery မှ တင်ခြင်းပိတ်ထားသည်',
  'Good': 'ကောင်းမွန်',
  'Goods Received': 'ပစ္စည်းလက်ခံရရှိမှု',
  'Goods Received Photo': 'လက်ခံရရှိပစ္စည်း ဓာတ်ပုံ',
  'Home': 'အိမ်',
  'Home Dashboard': 'ပင်မစာမျက်နှာ',
  'In Use': 'အသုံးပြုနေသည်',
  'Invoice': 'ဘောင်ချာ',
  'Invoice & goods check': 'ဘောင်ချာနှင့် ပစ္စည်းစစ်ဆေးမှု',
  'Invoice Photo': 'ဘောင်ချာဓာတ်ပုံ',
  'Invoice Qty': 'ဘောင်ချာအရေအတွက်',
  'Knowledge': 'အသိပညာ',
  'Knowledge Pool': 'အသိပညာ စုစည်းရာ',
  'Language': 'ဘာသာစကား',
  'English': 'အင်္ဂလိပ်',
  'Myanmar': 'မြန်မာ',
  'Linked Video': 'ချိတ်ဆက်ထားသော ဗီဒီယို',
  'No linked video': 'ချိတ်ဆက်ဗီဒီယို မရှိ',
  'Select Language': 'ဘာသာစကား ရွေးပါ',
  'Select Video Language': 'ဗီဒီယို ဘာသာစကား ရွေးပါ',
  'Select a previously created video': 'ယခင်ဖန်တီးထားသော ဗီဒီယိုကို ရွေးပါ',
  'SOP Details': 'SOP အသေးစိတ်',
  'Video Version': 'ဗီဒီယို ဗားရှင်း',
  'Video Versions': 'ဗီဒီယို ဗားရှင်းများ',
  'Language is fixed while two video versions are linked.':
      'ဗီဒီယို ဗားရှင်းနှစ်ခု ချိတ်ဆက်ထားချိန်တွင် ဘာသာစကားကို ပြောင်း၍မရပါ။',
  'Maximum two linked videos. Linked versions are deleted together.':
      'ချိတ်ဆက်ဗီဒီယို အများဆုံး နှစ်ခုသာ။ ချိတ်ဆက်ဗားရှင်းများကို အတူဖျက်ပါမည်။',
  'Last Updated': 'နောက်ဆုံးပြင်ဆင်မှု',
  'Leaderboard': 'အဆင့်ဇယား',
  'List users': 'အသုံးပြုသူစာရင်း',
  'Load Audit': 'စစ်ဆေးမှတ်တမ်း ဖွင့်ရန်',
  'Load More': 'ပိုမိုဖော်ပြရန်',
  'Loaded': 'ဖွင့်ပြီး',
  'Loading...': 'ဖွင့်နေသည်...',
  'Low': 'နည်းနေသည်',
  'Low Stock Only': 'ကုန်နည်းသည်များသာ',
  'Manage SOP': 'SOP စီမံရန်',
  'Manage businesses': 'လုပ်ငန်းများ စီမံရန်',
  'Manage roles': 'ရာထူးများ စီမံရန်',
  'Manage roles and availability.': 'ရာထူးနှင့် အသုံးပြုနိုင်မှုကို စီမံရန်။',
  'Manage users, roles and attendance': 'အသုံးပြုသူ၊ ရာထူးနှင့် တက်ရောက်မှု စီမံရန်',
  'Manager Score': 'မန်နေဂျာအမှတ်',
  'Max': 'အများဆုံး',
  'Max Balance': 'အများဆုံးလက်ကျန်',
  'Max Price': 'အမြင့်ဆုံးဈေး',
  'Maximum': 'အများဆုံး',
  'Maximum 30 days.': 'အများဆုံး ရက် ၃၀။',
  'Media selected': 'မီဒီယာ ရွေးပြီး',
  'Message': 'စာ',
  'Message copied to clipboard': 'စာကို clipboard သို့ ကူးယူပြီး',
  'Min': 'အနည်းဆုံး',
  'Min Balance': 'အနည်းဆုံးလက်ကျန်',
  'Min Price': 'အနိမ့်ဆုံးဈေး',
  'Minimum': 'အနည်းဆုံး',
  'Module': 'ကဏ္ဍ',
  'Nic\'s Kitchen': 'Nic\'s Kitchen',
  'No SKU found': 'SKU မတွေ့ပါ',
  'No SKU found.': 'SKU မတွေ့ပါ။',
  'No SKU matches the selected filters.': 'ရွေးထားသော စစ်ထုတ်မှုနှင့် ကိုက်ညီသည့် SKU မရှိပါ။',
  'No SOP found.': 'SOP မတွေ့ပါ။',
  'No audit trail found.': 'စစ်ဆေးမှတ်တမ်း မတွေ့ပါ။',
  'No backlog records found.': 'ကျန်ရှိမှတ်တမ်း မတွေ့ပါ။',
  'No daily count found.': 'နေ့စဉ်ရေတွက်မှု မတွေ့ပါ။',
  'No low-stock SKU today.': 'ယနေ့ ကုန်နည်း SKU မရှိပါ။',
  'No receiving records found.': 'ပစ္စည်းလက်ခံမှတ်တမ်း မတွေ့ပါ။',
  'No remark provided.': 'မှတ်ချက် မရှိပါ။',
  'No supplier found': 'ပေးသွင်းသူ မတွေ့ပါ',
  'No tag found': 'Tag မတွေ့ပါ',
  'No user available.': 'အသုံးပြုသူ မရှိပါ။',
  'Non editable. Manager or Head updates inside Stock Check.': 'ပြင်၍မရပါ။ Manager သို့မဟုတ် Head က Stock Check ထဲတွင် ပြင်ဆင်ရမည်။',
  'None': 'မရှိ',
  'Notes': 'မှတ်စုများ',
  'Open Camera': 'ကင်မရာဖွင့်ရန်',
  'Operation': 'လုပ်ငန်းစဉ်',
  'Optional camera proof': 'မလိုအပ်လျှင် ချန်ထားနိုင်သော ကင်မရာအထောက်အထား',
  'Overdue, rejected and approved records.': 'နောက်ကျ၊ ပယ်ချနှင့် အတည်ပြုမှတ်တမ်းများ။',
  'Password': 'စကားဝှက်',
  'Pending': 'စောင့်ဆိုင်း',
  'Pending Review': 'စစ်ဆေးရန် စောင့်ဆိုင်း',
  'Pending Reviews': 'စစ်ဆေးရန် စောင့်ဆိုင်း',
  'People': 'ဝန်ထမ်းများ',
  'People Dashboard': 'ဝန်ထမ်း စီမံခန့်ခွဲမှု',
  'Phone': 'ဖုန်း',
  'Phone Number': 'ဖုန်းနံပါတ်',
  'Photo Evidence': 'ဓာတ်ပုံအထောက်အထား',
  'Photo required': 'ဓာတ်ပုံ လိုအပ်သည်',
  'Photo selected': 'ဓာတ်ပုံ ရွေးပြီး',
  'Picture': 'ပုံ',
  'Please confirm these daily count records before applying bulk action.': 'အစုလိုက်လုပ်ဆောင်မှုမပြုမီ နေ့စဉ်ရေတွက်မှတ်တမ်းများကို အတည်ပြုပါ။',
  'Please confirm these receiving records before applying bulk action.': 'အစုလိုက်လုပ်ဆောင်မှုမပြုမီ လက်ခံမှတ်တမ်းများကို အတည်ပြုပါ။',
  'Please confirm these receiving records before submitting.': 'မတင်ပြမီ လက်ခံမှတ်တမ်းများကို အတည်ပြုပါ။',
  'Please enter valid numbers.': 'မှန်ကန်သော ကိန်းဂဏန်းများ ထည့်ပါ။',
  'Points Earned': 'ရရှိသော ပွိုင့်',
  'Points by Category': 'အမျိုးအစားအလိုက် ပွိုင့်',
  'Points earned': 'ရရှိသော ပွိုင့်',
  'Points/task': 'ပွိုင့်/တာဝန်',
  'Previous Value': 'ယခင်တန်ဖိုး',
  'Price': 'ဈေးနှုန်း',
  'Price must be Min / Max.': 'ဈေးနှုန်းသည် အနိမ့်ဆုံးနှင့် အမြင့်ဆုံးကြား ဖြစ်ရမည်။',
  'Purchase': 'ဝယ်ယူမှု',
  'Qty on invoice': 'ဘောင်ချာပါ အရေအတွက်',
  'Ready': 'အဆင်သင့်',
  'Received At': 'လက်ခံသည့်အချိန်',
  'Received By': 'လက်ခံသူ',
  'Received Qty': 'လက်ခံရရှိအရေအတွက်',
  'Receiving': 'ပစ္စည်းလက်ခံခြင်း',
  'Receiving Backlog': 'ပစ္စည်းလက်ခံမှု ကျန်ရှိစာရင်း',
  'Receiving Checklist': 'ပစ္စည်းလက်ခံ စစ်ဆေးစာရင်း',
  'Receiving Records': 'ပစ္စည်းလက်ခံမှတ်တမ်းများ',
  'Receiving Review': 'ပစ္စည်းလက်ခံမှု စစ်ဆေးရန်',
  'Receiving record approved': 'ပစ္စည်းလက်ခံမှတ်တမ်း အတည်ပြုပြီး',
  'Receiving record rejected': 'ပစ္စည်းလက်ခံမှတ်တမ်း ပယ်ချပြီး',
  'Receiving records approved': 'ပစ္စည်းလက်ခံမှတ်တမ်းများ အတည်ပြုပြီး',
  'Receiving records rejected': 'ပစ္စည်းလက်ခံမှတ်တမ်းများ ပယ်ချပြီး',
  'Report': 'အစီရင်ခံစာ',
  'Daily Photos': 'နေ့စဉ်ဓာတ်ပုံများ',
  'Photos Taken': 'ရိုက်ထားသောဓာတ်ပုံများ',
  'Receiving submitted': 'ပစ္စည်းလက်ခံမှု တင်ပြပြီး',
  'Recent Activity': 'လတ်တလော လှုပ်ရှားမှု',
  'Recent Rewards': 'လတ်တလော ဆုများ',
  'Recovery': 'ပြန်လည်ရယူမှု',
  'Redeem Points': 'ပွိုင့် လဲလှယ်ရန်',
  'Reject': 'ပယ်ချရန်',
  'Reject All': 'အားလုံး ပယ်ချရန်',
  'Reject reason, optional': 'ပယ်ချရသည့်အကြောင်းရင်း (မထည့်လည်းရ)',
  'Rejected': 'ပယ်ချပြီး',
  'Reload Audit': 'စစ်ဆေးမှတ်တမ်း ပြန်ဖွင့်ရန်',
  'Remark': 'မှတ်ချက်',
  'Remarks (Optional)': 'မှတ်ချက် (မထည့်လည်းရ)',
  'Required': 'လိုအပ်သည်',
  'Reset': 'ပြန်သတ်မှတ်ရန်',
  'Reset Time': 'ပြန်သတ်မှတ်ချိန်',
  'Reset Time required': 'ပြန်သတ်မှတ်ချိန် လိုအပ်သည်',
  'Restock': 'ကုန်ပြန်ဖြည့်ရန်',
  'Retake Photo': 'ဓာတ်ပုံ ပြန်ရိုက်ရန်',
  'Review': 'စစ်ဆေးရန်',
  'Review Note': 'စစ်ဆေးမှတ်ချက်',
  'Review Status': 'စစ်ဆေးအခြေအနေ',
  'Review Submission': 'တင်ပြမှု စစ်ဆေးရန်',
  'Review daily counts and receiving records.': 'နေ့စဉ်ရေတွက်မှုနှင့် ပစ္စည်းလက်ခံမှတ်တမ်းများကို စစ်ဆေးပါ။',
  'Review staff submissions and rate out of 10': 'ဝန်ထမ်းတင်ပြမှုများကို စစ်ဆေးပြီး ၁၀ မှတ်အတွင်း အမှတ်ပေးပါ',
  'Review the message, then copy and paste it to supplier chat.': 'စာကို စစ်ဆေးပြီး ပေးသွင်းသူ chat ထဲသို့ ကူးထည့်ပါ။',
  'Reviewed At': 'စစ်ဆေးသည့်အချိန်',
  'Reviewed By': 'စစ်ဆေးသူ',
  'Rewards': 'ဆုများ',
  'Role': 'ရာထူး',
  'SKU': 'SKU',
  'SKU Name': 'SKU အမည်',
  'SKU Photo': 'SKU ဓာတ်ပုံ',
  'SKU created': 'SKU ဖန်တီးပြီး',
  'SOP created. Staff can view it now.': 'SOP ဖန်တီးပြီး။ ဝန်ထမ်းများ ကြည့်နိုင်ပါပြီ။',
  'SOP deleted.': 'SOP ဖျက်ပြီးပါပြီ။',
  'SOPs deleted.': 'SOP များ ဖျက်ပြီးပါပြီ။',
  'SOP updated.': 'SOP ပြင်ဆင်ပြီးပါပြီ။',
  'Save': 'သိမ်းရန်',
  'Save SKU': 'SKU သိမ်းရန်',
  'Save Supplier': 'ပေးသွင်းသူ သိမ်းရန်',
  'Saved': 'သိမ်းပြီး',
  'Saving...': 'သိမ်းနေသည်...',
  'Schedule': 'အလုပ်ချိန်ဇယား',
  'Search': 'ရှာရန်',
  'Search SKU or user': 'SKU သို့မဟုတ် အသုံးပြုသူ ရှာရန်',
  'Search SOP...': 'SOP ရှာရန်...',
  'Search and edit users.': 'အသုံးပြုသူများကို ရှာပြီး ပြင်ဆင်ရန်။',
  'Search audit trail': 'စစ်ဆေးမှတ်တမ်း ရှာရန်',
  'Search backlog': 'ကျန်ရှိစာရင်း ရှာရန်',
  'Search daily count': 'နေ့စဉ်ရေတွက်မှု ရှာရန်',
  'Search receiving': 'ပစ္စည်းလက်ခံမှု ရှာရန်',
  'Search roles': 'ရာထူးများ ရှာရန်',
  'Search supplier': 'ပေးသွင်းသူ ရှာရန်',
  'Search tag': 'Tag ရှာရန်',
  'Search users': 'အသုံးပြုသူများ ရှာရန်',
  'Search, filter and edit SKU.': 'SKU ကို ရှာ၊ စစ်ထုတ်ပြီး ပြင်ဆင်ရန်။',
  'Select': 'ရွေးရန်',
  'Select Date Range': 'ရက်အပိုင်းအခြား ရွေးရန်',
  'Select SKU': 'SKU ရွေးရန်',
  'Select SKU first.': 'SKU ကို အရင်ရွေးပါ။',
  'Select SOP': 'SOP ရွေးရန်',
  'Select All': 'အားလုံးရွေးရန်',
  'selected': 'ခု ရွေးထားသည်',
  'Select Tag': 'Tag ရွေးရန်',
  'Select Video / Picture': 'ဗီဒီယို / ပုံ ရွေးရန်',
  'Select a date range, then load the audit trail.': 'ရက်အပိုင်းအခြားရွေးပြီး စစ်ဆေးမှတ်တမ်း ဖွင့်ပါ။',
  'Select at least one record': 'အနည်းဆုံး မှတ်တမ်းတစ်ခု ရွေးပါ',
  'Setup - Owner & Head': 'စနစ်ပြင်ဆင်မှု - Owner နှင့် Head',
  'Shift planning': 'အလုပ်ချိန် စီစဉ်မှု',
  'Showing': 'ပြသနေသည်',
  'Sign In': 'ဝင်ရောက်ရန်',
  'Staff Remark': 'ဝန်ထမ်းမှတ်ချက်',
  'Standard Operating Procedure': 'စံလုပ်ငန်းစဉ်',
  'State changes only. Select up to 30 days.': 'အခြေအနေပြောင်းလဲမှုများသာ။ ရက် ၃၀ အထိ ရွေးနိုင်သည်။',
  'Status': 'အခြေအနေ',
  'Stock': 'ကုန်ပစ္စည်း',
  'Stock Balance': 'ကုန်လက်ကျန်',
  'Stock Dashboard': 'ကုန်ပစ္စည်း စီမံခန့်ခွဲမှု',
  'Stock Level': 'ကုန်လက်ကျန်အဆင့်',
  'Stock Thumbnail': 'ကုန်ပစ္စည်းပုံငယ်',
  'Stock Thumbnail required': 'ကုန်ပစ္စည်းပုံငယ် လိုအပ်သည်',
  'Submissions Reviewed': 'စစ်ဆေးပြီးသော တင်ပြမှုများ',
  'Submit All': 'အားလုံး တင်ပြရန်',
  'Submit Daily Count': 'နေ့စဉ်ရေတွက်မှု တင်ပြရန်',
  'Submit Task': 'တာဝန်တင်ပြရန်',
  'Submit for Approval': 'အတည်ပြုရန် တင်ပြပါ',
  'Submitted': 'တင်ပြပြီး',
  'Submitted just now': 'ယခုတင်ပြပြီး',
  'Submitted recently': 'မကြာသေးမီက တင်ပြပြီး',
  'Supplier': 'ပေးသွင်းသူ',
  'Supplier Name': 'ပေးသွင်းသူအမည်',
  'Supplier Purchase Setup': 'ပေးသွင်းသူ ဝယ်ယူမှုစနစ်',
  'Supplier created': 'ပေးသွင်းသူ ဖန်တီးပြီး',
  'Supplier purchase setup is managed by Head': 'ပေးသွင်းသူဝယ်ယူမှုစနစ်ကို Head က စီမံသည်',
  'Supplier required': 'ပေးသွင်းသူ လိုအပ်သည်',
  'Supplier restock message copied': 'ပေးသွင်းသူထံ ကုန်ပြန်ဖြည့်စာ ကူးယူပြီး',
  'Suppliers': 'ပေးသွင်းသူများ',
  'Suppliers link inside SKU Setup.': 'ပေးသွင်းသူချိတ်ဆက်မှုကို SKU Setup ထဲတွင် စီမံသည်။',
  'Tag': 'Tag',
  'Tag 1': 'Tag 1',
  'Tag 1 required': 'Tag 1 လိုအပ်သည်',
  'Tag 2': 'Tag 2',
  'Tag 2 required': 'Tag 2 လိုအပ်သည်',
  'Tag already exists': 'Tag ရှိပြီးသားဖြစ်သည်',
  'Tag is required': 'Tag လိုအပ်သည်',
  'Take Photo': 'ဓာတ်ပုံရိုက်ရန်',
  'Take a fresh photo of the supplier invoice.': 'ပေးသွင်းသူဘောင်ချာကို အသစ်ပြန်ရိုက်ပါ။',
  'Take one photo showing the goods received for this supplier.': 'ဤပေးသွင်းသူထံမှ လက်ခံရရှိသောပစ္စည်းများကို ဓာတ်ပုံတစ်ပုံရိုက်ပါ။',
  'Tap photo to view. Tap balance to update.': 'ကြည့်ရန် ဓာတ်ပုံကို နှိပ်ပါ။ ပြင်ရန် လက်ကျန်ကို နှိပ်ပါ။',
  'Tap supplier to preview message.': 'စာကြိုကြည့်ရန် ပေးသွင်းသူကို နှိပ်ပါ။',
  'Task Approvals': 'တာဝန် အတည်ပြုမှုများ',
  'Task approved': 'တာဝန် အတည်ပြုပြီး',
  'Task rejected': 'တာဝန် ပယ်ချပြီး',
  'Task submitted for manager approval': 'မန်နေဂျာ အတည်ပြုရန် တာဝန်တင်ပြပြီး',
  'Tasks': 'တာဝန်များ',
  'Tasks Completed': 'ပြီးစီးသော တာဝန်များ',
  'Tasks done': 'ပြီးစီးသော တာဝန်များ',
  'Reports done': 'ပြီးစီးသော အစီရင်ခံစာများ',
  'This Month': 'ဒီလ',
  'This Week': 'ဒီအပတ်',
  'Timer': 'အချိန်တွက်စက်',
  'Title': 'ခေါင်းစဉ်',
  'Today': 'ယနေ့',
  'Today\'s Progress': 'ယနေ့ တိုးတက်မှု',
  'Today\'s Reviews': 'ယနေ့ စစ်ဆေးမှု',
  'Total': 'စုစုပေါင်း',
  'Total Points': 'စုစုပေါင်း ပွိုင့်',
  'Total Points Balance': 'စုစုပေါင်း ပွိုင့် လက်ကျန်',
  'Total SKU': 'SKU စုစုပေါင်း',
  'Track your points and achievements': 'ပွိုင့်နှင့် အောင်မြင်မှုများကို ကြည့်ရန်',
  'Transparent point ranking': 'ပွိုင့်အဆင့်ဇယား',
  'Unassigned': 'တာဝန်မပေးရသေး',
  'Unassigned Supplier': 'ပေးသွင်းသူ မသတ်မှတ်ရသေး',
  'Unit': 'ယူနစ်',
  'Up 3 ranks': 'အဆင့် ၃ ဆင့် တက်',
  'Update daily physical stock balance': 'နေ့စဉ် အမှန်တကယ်ကုန်လက်ကျန် ပြင်ဆင်ရန်',
  'Upload Photo Evidence *': 'ဓာတ်ပုံအထောက်အထား တင်ရန် *',
  'Upload Video / Picture': 'ဗီဒီယို / ပုံ တင်ရန်',
  'User': 'အသုံးပြုသူ',
  'Valid number required': 'မှန်ကန်သော ကိန်းဂဏန်း လိုအပ်သည်',
  'Video': 'ဗီဒီယို',
  'Video tutorial available': 'ဗီဒီယိုလမ်းညွှန် ရှိသည်',
  'View SOP': 'SOP ကြည့်ရန်',
  'View Tasks': 'တာဝန်များကြည့်ရန်',
  'View attendance': 'တက်ရောက်မှု ကြည့်ရန်',
  'View roles': 'ရာထူးများ ကြည့်ရန်',
  'View roles.': 'ရာထူးများ ကြည့်ရန်။',
  'View users.': 'အသုံးပြုသူများ ကြည့်ရန်။',
  'Watch Video': 'ဗီဒီယိုကြည့်ရန်',
  'Your Current Rank': 'လက်ရှိအဆင့်',
  'approved': 'အတည်ပြုပြီး',
  'completed': 'ပြီးစီးပြီး',
  'in_progress': 'လုပ်ဆောင်နေ',
  'items': 'ပစ္စည်း',
  'pending': 'စောင့်ဆိုင်း',
  'points': 'ပွိုင့်',
  'points earned': 'ပွိုင့် ရရှိပြီး',
  'rejected': 'ပယ်ချပြီး',
  'submitted': 'တင်ပြပြီး',
  'user': 'အသုံးပြုသူ',
};

const Map<String, String> _chinese = {
  '\$label required': '\$label为必填项',
  'Access SOPs, recipes, and ingredients': '查看SOP、食谱和食材',
  'Active': '启用',
  'Advertisement': '广告',
  'Actor': '操作人',
  'Actors': '操作人',
  'Actual received': '实际收货',
  'Add SKU': '添加SKU',
  'Add Supplier': '添加供应商',
  'Add Tag': '添加标签',
  'Add any additional notes...': '添加其他备注……',
  'Address': '地址',
  'All': '全部',
  'All Time': '全部时间',
  'All supplier messages copied': '已复制所有供应商消息',
  'Apply': '应用',
  'Approvals': '审批',
  'Approve': '批准',
  'Approve All': '全部批准',
  'Approved': '已批准',
  'Assign': '分配',
  'Assign SKU to user': '将SKU分配给用户',
  'Assign SKU to user.': '将SKU分配给用户。',
  'Assigned': '已分配',
  'Assigned tags cannot be deleted': '已使用的标签无法删除',
  'Assignee': '负责人',
  'Assignee updated': '负责人已更新',
  'Attendance': '考勤',
  'Attendance reports': '考勤报告',
  'Audit': '审计',
  'Audit Inbound': '入库审计',
  'Audit Trail': '审计记录',
  'Available for redemption': '可用于兑换',
  'Average': '平均',
  'Back': '返回',
  'Backlog': '待处理',
  'Balance': '库存量',
  'Balance must be Min / Max.': '库存量必须在最小值与最大值之间。',
  'Business': '业务',
  'Camera only': '仅限相机',
  'Camera photo captured': '已拍摄照片',
  'Cancel': '取消',
  'Capture photos, then SKU.': '先拍照，再选择SKU。',
  'Captured': '已拍摄',
  'Career Path': '职业发展',
  'Change log': '变更记录',
  'Changed Value': '变更值',
  'Checklist': '检查清单',
  'Checklist \${index + 1}': '检查项 \${index + 1}',
  'Checklist checked': '检查清单已确认',
  'Clear': '清除',
  'Clear All': '全部清除',
  'Click to upload photo': '点击上传照片',
  'Clock in/out': '上下班打卡',
  'Company ID': '公司ID',
  'Complete all fields.': '请填写所有字段。',
  'Complete tasks to earn points': '完成任务以获得积分',
  'Completed': '已完成',
  'Confirm': '确认',
  'Confirm Approve All': '确认全部批准',
  'Confirm Reject All': '确认全部拒绝',
  'Confirm Submit All': '确认全部提交',
  'Contact': '联系人',
  'Contact Person': '联系人',
  'Copy Message': '复制消息',
  'Count': '盘点',
  'Count stock / receive goods / prepare restock': '盘点库存／收货／准备补货',
  'Counted By': '盘点人',
  'Create New SOP': '新建SOP',
  'Create Role': '创建角色',
  'Create SOP': '创建SOP',
  'Create Supplier': '创建供应商',
  'Create User': '创建用户',
  'Create a Tag in Stock first.': '请先在库存中创建标签。',
  'Create supplier first': '请先创建供应商',
  'Create suppliers': '创建供应商',
  'Create tag first': '请先创建标签',
  'Create/list SKU': '创建／查看SKU',
  'Create/list Supplier': '创建／查看供应商',
  'Created By': '创建人',
  'Created Date': '创建日期',
  'Current': '当前',
  'Current Balance': '当前库存量',
  'Current Stock': '当前库存',
  'Custom Category': '自定义分类',
  'Daily Count Backlog': '每日盘点待处理',
  'Daily Count Records': '每日盘点记录',
  'Daily Count Review': '每日盘点审核',
  'Daily Tasks': '每日任务',
  'Daily count approved': '每日盘点已批准',
  'Daily count records approved': '每日盘点记录已批准',
  'Daily count records rejected': '每日盘点记录已拒绝',
  'Daily count rejected': '每日盘点已拒绝',
  'Daily stock count submitted': '每日库存盘点已提交',
  'Delete': '删除',
  'Deleted': '已删除',
  'Description': '说明',
  'Description:': '说明：',
  'Edit': '编辑',
  'Edit SOP': '编辑SOP',
  'Employee ID': '员工ID',
  'Enter a valid phone number.': '请输入有效的电话号码。',
  'Enter your password': '请输入密码',
  'Entries': '记录数',
  'Example: 0123456789': '例如：0123456789',
  'Example: 1kg damaged / item missing': '例如：损坏1公斤／物品缺失',
  'Example: Chicken': '例如：鸡肉',
  'Example: Chiller': '例如：冷藏',
  'Example: Fresh Farm Supplier': '例如：Fresh Farm供应商',
  'Example: GTI Kampar': '例如：GTI Kampar',
  'Example: Mr Tan': '例如：陈先生',
  'Expected Outcome:': '预期结果：',
  'Filter by assignee': '按负责人筛选',
  'Gallery upload disabled': '已禁用相册上传',
  'Good': '正常',
  'Goods Received': '已收货',
  'Goods Received Photo': '收货照片',
  'Home': '主页',
  'Home Dashboard': '主页概览',
  'In Use': '使用中',
  'Invoice': '发票',
  'Invoice & goods check': '发票与货物检查',
  'Invoice Photo': '发票照片',
  'Invoice Qty': '发票数量',
  'Knowledge': '知识',
  'Knowledge Pool': '知识库',
  'Language': '语言',
  'English': '英语',
  'Myanmar': '缅甸语',
  'Linked Video': '关联视频',
  'No linked video': '不关联视频',
  'Select Language': '选择语言',
  'Select Video Language': '选择视频语言',
  'Select a previously created video': '选择之前创建的视频',
  'SOP Details': 'SOP详情',
  'Video Version': '视频版本',
  'Video Versions': '视频版本',
  'Language is fixed while two video versions are linked.':
      '关联两个视频版本后，不能更改语言。',
  'Maximum two linked videos. Linked versions are deleted together.':
      '最多关联两个视频，关联版本会一起删除。',
  'Last Updated': '最后更新',
  'Leaderboard': '排行榜',
  'List users': '用户列表',
  'Load Audit': '加载审计记录',
  'Load More': '加载更多',
  'Loaded': '已加载',
  'Loading...': '加载中……',
  'Low': '不足',
  'Low Stock Only': '仅显示低库存',
  'Manage SOP': '管理SOP',
  'Manage businesses': '管理业务',
  'Manage roles': '管理角色',
  'Manage roles and availability.': '管理角色及启用状态。',
  'Manage users, roles and attendance': '管理用户、角色和考勤',
  'Manager Score': '经理评分',
  'Max': '最大',
  'Max Balance': '最大库存量',
  'Max Price': '最高价格',
  'Maximum': '最大值',
  'Maximum 30 days.': '最多30天。',
  'Media selected': '已选择媒体',
  'Message': '消息',
  'Message copied to clipboard': '消息已复制到剪贴板',
  'Min': '最小',
  'Min Balance': '最小库存量',
  'Min Price': '最低价格',
  'Minimum': '最小值',
  'Module': '模块',
  'Nic\'s Kitchen': 'Nic\'s Kitchen',
  'No SKU found': '找不到SKU',
  'No SKU found.': '找不到SKU。',
  'No SKU matches the selected filters.': '没有符合所选筛选条件的SKU。',
  'No SOP found.': '找不到SOP。',
  'No audit trail found.': '找不到审计记录。',
  'No backlog records found.': '找不到待处理记录。',
  'No daily count found.': '找不到每日盘点记录。',
  'No low-stock SKU today.': '今天没有低库存SKU。',
  'No receiving records found.': '找不到收货记录。',
  'No remark provided.': '未提供备注。',
  'No supplier found': '找不到供应商',
  'No tag found': '找不到标签',
  'No user available.': '没有可用用户。',
  'Non editable. Manager or Head updates inside Stock Check.': '不可编辑。由经理或Head在库存检查中更新。',
  'None': '无',
  'Notes': '备注',
  'Open Camera': '打开相机',
  'Operation': '操作',
  'Optional camera proof': '可选相机凭证',
  'Overdue, rejected and approved records.': '逾期、已拒绝及已批准的记录。',
  'Password': '密码',
  'Pending': '待处理',
  'Pending Review': '待审核',
  'Pending Reviews': '待审核',
  'People': '人员',
  'People Dashboard': '人员概览',
  'Phone': '电话',
  'Phone Number': '电话号码',
  'Photo Evidence': '照片凭证',
  'Photo required': '必须提供照片',
  'Photo selected': '已选择照片',
  'Picture': '图片',
  'Please confirm these daily count records before applying bulk action.': '批量操作前，请确认这些每日盘点记录。',
  'Please confirm these receiving records before applying bulk action.': '批量操作前，请确认这些收货记录。',
  'Please confirm these receiving records before submitting.': '提交前，请确认这些收货记录。',
  'Please enter valid numbers.': '请输入有效数字。',
  'Points Earned': '已获得积分',
  'Points by Category': '按分类统计积分',
  'Points earned': '已获得积分',
  'Points/task': '积分／任务',
  'Previous Value': '原值',
  'Price': '价格',
  'Price must be Min / Max.': '价格必须在最低价与最高价之间。',
  'Purchase': '采购',
  'Qty on invoice': '发票数量',
  'Ready': '就绪',
  'Received At': '收货时间',
  'Received By': '收货人',
  'Received Qty': '收货数量',
  'Receiving': '收货',
  'Receiving Backlog': '收货待处理',
  'Receiving Checklist': '收货检查清单',
  'Receiving Records': '收货记录',
  'Receiving Review': '收货审核',
  'Receiving record approved': '收货记录已批准',
  'Receiving record rejected': '收货记录已拒绝',
  'Receiving records approved': '收货记录已批准',
  'Receiving records rejected': '收货记录已拒绝',
  'Report': '报告',
  'Daily Photos': '每日照片',
  'Photos Taken': '已拍照片',
  'Receiving submitted': '收货记录已提交',
  'Recent Activity': '最近活动',
  'Recent Rewards': '最近奖励',
  'Recovery': '恢复',
  'Redeem Points': '兑换积分',
  'Reject': '拒绝',
  'Reject All': '全部拒绝',
  'Reject reason, optional': '拒绝原因（可选）',
  'Rejected': '已拒绝',
  'Reload Audit': '重新加载审计记录',
  'Remark': '备注',
  'Remarks (Optional)': '备注（可选）',
  'Required': '必填',
  'Reset': '重置',
  'Reset Time': '重置时间',
  'Reset Time required': '必须填写重置时间',
  'Restock': '补货',
  'Retake Photo': '重新拍照',
  'Review': '审核',
  'Review Note': '审核备注',
  'Review Status': '审核状态',
  'Review Submission': '审核提交内容',
  'Review daily counts and receiving records.': '审核每日盘点及收货记录。',
  'Review staff submissions and rate out of 10': '审核员工提交内容并以10分制评分',
  'Review the message, then copy and paste it to supplier chat.': '检查消息后，复制并粘贴到供应商聊天。',
  'Reviewed At': '审核时间',
  'Reviewed By': '审核人',
  'Rewards': '奖励',
  'Role': '角色',
  'SKU': 'SKU',
  'SKU Name': 'SKU名称',
  'SKU Photo': 'SKU照片',
  'SKU created': 'SKU已创建',
  'SOP created. Staff can view it now.': 'SOP已创建，员工现在可以查看。',
  'SOP deleted.': 'SOP已删除。',
  'SOPs deleted.': 'SOP已删除。',
  'SOP updated.': 'SOP已更新。',
  'Save': '保存',
  'Save SKU': '保存SKU',
  'Save Supplier': '保存供应商',
  'Saved': '已保存',
  'Saving...': '保存中……',
  'Schedule': '排班',
  'Search': '搜索',
  'Search SKU or user': '搜索SKU或用户',
  'Search SOP...': '搜索SOP……',
  'Search and edit users.': '搜索并编辑用户。',
  'Search audit trail': '搜索审计记录',
  'Search backlog': '搜索待处理记录',
  'Search daily count': '搜索每日盘点',
  'Search receiving': '搜索收货记录',
  'Search roles': '搜索角色',
  'Search supplier': '搜索供应商',
  'Search tag': '搜索标签',
  'Search users': '搜索用户',
  'Search, filter and edit SKU.': '搜索、筛选并编辑SKU。',
  'Select': '选择',
  'Select Date Range': '选择日期范围',
  'Select SKU': '选择SKU',
  'Select SKU first.': '请先选择SKU。',
  'Select SOP': '选择SOP',
  'Select All': '全选',
  'selected': '项已选择',
  'Select Tag': '选择标签',
  'Select Video / Picture': '选择视频／图片',
  'Select a date range, then load the audit trail.': '请选择日期范围，然后加载审计记录。',
  'Select at least one record': '请至少选择一条记录',
  'Setup - Owner & Head': '设置－Owner与Head',
  'Shift planning': '排班规划',
  'Showing': '显示中',
  'Sign In': '登录',
  'Staff Remark': '员工备注',
  'Standard Operating Procedure': '标准作业程序',
  'State changes only. Select up to 30 days.': '仅显示状态变更。最多选择30天。',
  'Status': '状态',
  'Stock': '库存',
  'Stock Balance': '库存量',
  'Stock Dashboard': '库存概览',
  'Stock Level': '库存水平',
  'Stock Thumbnail': '库存缩略图',
  'Stock Thumbnail required': '必须提供库存缩略图',
  'Submissions Reviewed': '已审核提交',
  'Submit All': '全部提交',
  'Submit Daily Count': '提交每日盘点',
  'Submit Task': '提交任务',
  'Submit for Approval': '提交审批',
  'Submitted': '已提交',
  'Submitted just now': '刚刚提交',
  'Submitted recently': '最近提交',
  'Supplier': '供应商',
  'Supplier Name': '供应商名称',
  'Supplier Purchase Setup': '供应商采购设置',
  'Supplier created': '供应商已创建',
  'Supplier purchase setup is managed by Head': '供应商采购设置由Head管理',
  'Supplier required': '必须选择供应商',
  'Supplier restock message copied': '供应商补货消息已复制',
  'Suppliers': '供应商',
  'Suppliers link inside SKU Setup.': '供应商关联在SKU设置中管理。',
  'Tag': '标签',
  'Tag 1': '标签1',
  'Tag 1 required': '必须选择标签1',
  'Tag 2': '标签2',
  'Tag 2 required': '必须选择标签2',
  'Tag already exists': '标签已存在',
  'Tag is required': '必须选择标签',
  'Take Photo': '拍照',
  'Take a fresh photo of the supplier invoice.': '请重新拍摄供应商发票。',
  'Take one photo showing the goods received for this supplier.': '请拍摄一张显示该供应商收货情况的照片。',
  'Tap photo to view. Tap balance to update.': '点击照片查看；点击库存量更新。',
  'Tap supplier to preview message.': '点击供应商预览消息。',
  'Task Approvals': '任务审批',
  'Task approved': '任务已批准',
  'Task rejected': '任务已拒绝',
  'Task submitted for manager approval': '任务已提交经理审批',
  'Tasks': '任务',
  'Tasks Completed': '已完成任务',
  'Tasks done': '已完成任务',
  'Reports done': '已完成报告',
  'This Month': '本月',
  'This Week': '本周',
  'Timer': '计时器',
  'Title': '标题',
  'Today': '今天',
  'Today\'s Progress': '今日进度',
  'Today\'s Reviews': '今日审核',
  'Total': '总计',
  'Total Points': '总积分',
  'Total Points Balance': '总积分余额',
  'Total SKU': 'SKU总数',
  'Track your points and achievements': '追踪积分与成就',
  'Transparent point ranking': '透明积分排名',
  'Unassigned': '未分配',
  'Unassigned Supplier': '未分配供应商',
  'Unit': '单位',
  'Up 3 ranks': '上升3名',
  'Update daily physical stock balance': '更新每日实际库存量',
  'Upload Photo Evidence *': '上传照片凭证 *',
  'Upload Video / Picture': '上传视频／图片',
  'User': '用户',
  'Valid number required': '必须输入有效数字',
  'Video': '视频',
  'Video tutorial available': '提供视频教程',
  'View SOP': '查看SOP',
  'View Tasks': '查看任务',
  'View attendance': '查看考勤',
  'View roles': '查看角色',
  'View roles.': '查看角色。',
  'View users.': '查看用户。',
  'Watch Video': '观看视频',
  'Your Current Rank': '当前排名',
  'approved': '已批准',
  'completed': '已完成',
  'in_progress': '进行中',
  'items': '项',
  'pending': '待处理',
  'points': '积分',
  'points earned': '已获得积分',
  'rejected': '已拒绝',
  'submitted': '已提交',
  'user': '用户',
};
