name: east_app
description: EastApp prototype
publish_to: 'none'
version: 1.0.0+334

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: '>=3.38.1'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.8.1
  camera: ^0.12.0+2
  geolocator: ^14.0.3
  mobile_scanner: ^7.4.0
  qr_flutter: ^4.1.0
  geocoding: ^5.0.0
  http: ^1.6.0
  image_picker: ^1.2.3
