name: east_app
description: EastApp prototype
publish_to: 'none'
version: 1.0.0+318

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: '>=3.38.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.8.1
  camera: ^0.12.0+2
  geolocator: ^14.0.3
  mobile_scanner: ^7.4.0
  qr_flutter: ^4.1.0
  geocoding: ^5.0.0
  http: ^1.6.0
  image_picker: ^1.2.3
  flutter_secure_storage: ^11.0.0
  flutter_contacts: 2.1.0
  firebase_core: ^4.14.0
  firebase_messaging: ^16.6.0
  file_picker: ^12.1.3
  youtube_player_iframe: ^6.0.2
  uuid: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png
    - assets/sounds/01_success_pop.wav

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "assets/app_icon_background.png"
  adaptive_icon_foreground: "assets/app_icon_foreground.png"
